### ISSUE TITLE
Meta update missing

### ISSUE THREAD

**Issue by braunjon** [eric-mitchell/macaw-min#1]
I think the meta update of the policy and the value function is missing.

After the inner loop https://github.com/eric-mitchell/macaw-min/blob/e39eb607e5b37f7e029ab224958d0b5d013fa124/impl.py#L136 over the tasks has finished I think we should update the meta models.
```
policy_opt.step()
policy_opt.zero_grad()
vf_opt.step()
vf_opt.zero_grad()
```

**Comment by eric-mitchell** [comment]
Thanks for bringing this up- I just pushed https://github.com/eric-mitchell/macaw-min/commit/24d92051336c9c2b9f8e10e29cc58dbfc31be010 to correct this.

I'll close this for now, but please re-open if you have any other issues!
